#!/bin/bash
echo "=== Build Diagnostic $(date) ==="
echo "Log lines: $(wc -l < /tmp/rebuild-out.log)"
echo ""
echo "--- Last 20 lines ---"
tail -20 /tmp/rebuild-out.log
echo ""
echo "--- Errors ---"
grep -i 'error\|fail\|fatal\|BUILD' /tmp/rebuild-out.log 2>/dev/null || echo "(none)"
echo ""
echo "--- APK files ---"
find /home/liuhui/lingjing/mobile/android -name '*.apk' 2>/dev/null || echo "(none)"
echo ""
echo "--- Running Gradle processes ---"
ps aux 2>/dev/null | grep -i gradle | grep -v grep || echo "(none)"
