version: 1.73.89
files:
  - url: 1.73.89/LingJing-1.73.89-linux-x86_64.AppImage
    sha512: UvTTzN4pMdOf8SFaWDGpGecNa84D6QAdMJilHWsUmXLXYRaSdzxsOB5bjVoN725/A1cvvbhM6JSOrLAgvmXLqQ==
    size: 255283201
  - url: 1.73.89/LingJing-1.73.89-linux-x86_64.deb
    sha512: 6HWz1R4bOnaelK5jma05uQcoD/ncQ91GDexxfZ9H7zpzY0Bz7tRB0wpKSDAAPcxeIIpQ1tJNaVrrnr/g2h/2aw==
    size: 129941408
path: 1.73.89/LingJing-1.73.89-linux-x86_64.AppImage
sha512: UvTTzN4pMdOf8SFaWDGpGecNa84D6QAdMJilHWsUmXLXYRaSdzxsOB5bjVoN725/A1cvvbhM6JSOrLAgvmXLqQ==
releaseDate: '2026-06-16T02:19:48.690Z'
