version: 1.73.90
files:
  - url: 1.73.90/灵境 Setup 1.73.90.exe
    sha512: 4nMF4eF5VncCaJwDBLLWJAVaCvWzgMxt/5zlU7Gy9/XlrC0YSGAoMl59eOgMXzaZMbhtfCofH3fsNi6sMHk2Bw==
    size: 195085342
path: 1.73.90/灵境 Setup 1.73.90.exe
sha512: 4nMF4eF5VncCaJwDBLLWJAVaCvWzgMxt/5zlU7Gy9/XlrC0YSGAoMl59eOgMXzaZMbhtfCofH3fsNi6sMHk2Bw==
releaseDate: '2026-06-16T02:54:19.048Z'
