version: 1.72.31
files:
  - url: 灵境 Setup 1.72.31.exe
    sha512: fKrhHuA2rcSwGVeJFgVkc6jzes3OnBJEeD8ZPO0r7Ha7NcaEdiyuox2uaqTnrI6z7cBzyNsPa9S2h+lYyhOXfQ==
    size: 145759462
path: 灵境 Setup 1.72.31.exe
sha512: fKrhHuA2rcSwGVeJFgVkc6jzes3OnBJEeD8ZPO0r7Ha7NcaEdiyuox2uaqTnrI6z7cBzyNsPa9S2h+lYyhOXfQ==
releaseDate: '2026-06-11T08:31:37.190Z'
