version: 1.72.29
files:
  - url: LingJing-Setup-1.72.31-win-x64.exe
    sha512: fKrhHuA2rcSwGVeJFgVkc6jzes3OnBJEeD8ZPO0r7Ha7NcaEdiyuox2uaqTnrI6z7cBzyNsPa9S2h+lYyhOXfQ==
    size: 145759462
path: LingJing-Setup-1.72.31-win-x64.exe
sha512: fKrhHuA2rcSwGVeJFgVkc6jzes3OnBJEeD8ZPO0r7Ha7NcaEdiyuox2uaqTnrI6z7cBzyNsPa9S2h+lYyhOXfQ==
releaseDate: '2026-06-11T08:31:37.190Z'
