-- 009_biz_tables.sql
-- 补齐 biz_* 表缺失的业务字段
-- 执行方式: psql -d lingjing -f 009_biz_tables.sql

-- 1. biz_contracts
ALTER TABLE biz_contracts ADD COLUMN IF NOT EXISTS tenant_id VARCHAR(64) NOT NULL DEFAULT '';
ALTER TABLE biz_contracts ADD COLUMN IF NOT EXISTS project_id INTEGER;
ALTER TABLE biz_contracts ADD COLUMN IF NOT EXISTS contract_no VARCHAR(100) NOT NULL DEFAULT '';
ALTER TABLE biz_contracts ADD COLUMN IF NOT EXISTS title VARCHAR(200) NOT NULL DEFAULT '';
ALTER TABLE biz_contracts ADD COLUMN IF NOT EXISTS party_a VARCHAR(200) NOT NULL DEFAULT '';
ALTER TABLE biz_contracts ADD COLUMN IF NOT EXISTS party_b VARCHAR(200) NOT NULL DEFAULT '';
ALTER TABLE biz_contracts ADD COLUMN IF NOT EXISTS amount NUMERIC(12,2) NOT NULL DEFAULT 0;
ALTER TABLE biz_contracts ADD COLUMN IF NOT EXISTS sign_date DATE;
ALTER TABLE biz_contracts ADD COLUMN IF NOT EXISTS start_date DATE;
ALTER TABLE biz_contracts ADD COLUMN IF NOT EXISTS end_date DATE;
ALTER TABLE biz_contracts ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'draft';
ALTER TABLE biz_contracts ADD COLUMN IF NOT EXISTS file_url TEXT NOT NULL DEFAULT '';
ALTER TABLE biz_contracts ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE biz_contracts ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

-- 2. biz_customers
ALTER TABLE biz_customers ADD COLUMN IF NOT EXISTS tenant_id VARCHAR(64) NOT NULL DEFAULT '';
ALTER TABLE biz_customers ADD COLUMN IF NOT EXISTS contact_person VARCHAR(100) NOT NULL DEFAULT '';
ALTER TABLE biz_customers ADD COLUMN IF NOT EXISTS phone VARCHAR(50) NOT NULL DEFAULT '';
ALTER TABLE biz_customers ADD COLUMN IF NOT EXISTS company VARCHAR(200) NOT NULL DEFAULT '';
ALTER TABLE biz_customers ADD COLUMN IF NOT EXISTS source VARCHAR(50) NOT NULL DEFAULT '';
ALTER TABLE biz_customers ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'active';
ALTER TABLE biz_customers ADD COLUMN IF NOT EXISTS notes TEXT NOT NULL DEFAULT '';
ALTER TABLE biz_customers ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE biz_customers ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

-- 3. biz_suppliers
ALTER TABLE biz_suppliers ADD COLUMN IF NOT EXISTS tenant_id VARCHAR(64) NOT NULL DEFAULT '';
ALTER TABLE biz_suppliers ADD COLUMN IF NOT EXISTS contact_person VARCHAR(100) NOT NULL DEFAULT '';
ALTER TABLE biz_suppliers ADD COLUMN IF NOT EXISTS phone VARCHAR(50) NOT NULL DEFAULT '';
ALTER TABLE biz_suppliers ADD COLUMN IF NOT EXISTS category VARCHAR(100) NOT NULL DEFAULT '';
ALTER TABLE biz_suppliers ADD COLUMN IF NOT EXISTS material_type VARCHAR(100) NOT NULL DEFAULT '';
ALTER TABLE biz_suppliers ADD COLUMN IF NOT EXISTS business_type VARCHAR(50) NOT NULL DEFAULT '';
ALTER TABLE biz_suppliers ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'prospect';
ALTER TABLE biz_suppliers ADD COLUMN IF NOT EXISTS rating INTEGER NOT NULL DEFAULT 0;
ALTER TABLE biz_suppliers ADD COLUMN IF NOT EXISTS address TEXT NOT NULL DEFAULT '';
ALTER TABLE biz_suppliers ADD COLUMN IF NOT EXISTS notes TEXT NOT NULL DEFAULT '';
ALTER TABLE biz_suppliers ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE biz_suppliers ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

-- 4. biz_projects
ALTER TABLE biz_projects ADD COLUMN IF NOT EXISTS tenant_id VARCHAR(64) NOT NULL DEFAULT '';
ALTER TABLE biz_projects ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'active';
ALTER TABLE biz_projects ADD COLUMN IF NOT EXISTS description TEXT NOT NULL DEFAULT '';
ALTER TABLE biz_projects ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE biz_projects ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

-- 5. sample_records - 补齐缺失字段
ALTER TABLE sample_records ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE sample_records ADD COLUMN IF NOT EXISTS notes TEXT NOT NULL DEFAULT '';
