/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: {
          50: '#e6f1ff',
          100: '#cce3ff',
          200: '#99c7ff',
          300: '#66abff',
          400: '#338fff',
          500: '#007acc',
          600: '#0062a3',
          700: '#00497a',
          800: '#003152',
          900: '#001829',
        },
        neutral: {
          0: 'var(--cp-bg, #ffffff)',
          50: 'var(--cp-tab-inactive, #fafafa)',
          100: 'var(--cp-tab-inactive, #f5f5f5)',
          200: 'var(--cp-border, #e5e5e5)',
          300: 'var(--cp-border, #d4d4d4)',
          400: 'var(--cp-text-dim, #a3a3a3)',
          500: 'var(--cp-text-dim, #737373)',
          600: 'var(--cp-text-dim, #525252)',
          700: 'var(--cp-text-dim, #404040)',
          800: 'var(--cp-sidebar, #262626)',
          900: 'var(--cp-bg, #171717)',
          950: 'var(--cp-bg, #0a0a0a)',
        },
        success: {
          light: '#059669',
          dark: '#4ec9b0',
        },
        error: {
          light: '#dc2626',
          dark: '#f44747',
        },
        warning: {
          light: '#d97706',
          dark: '#cca700',
        },
        info: {
          light: '#2563eb',
          dark: '#3794ff',
        },
        'cp-bg': 'var(--cp-bg, #1e1e1e)',
        'cp-sidebar': 'var(--cp-sidebar, #252526)',
        'cp-editor': 'var(--cp-editor, #1e1e1e)',
        'cp-panel': 'var(--cp-panel, #1e1e1e)',
        'cp-statusbar': 'var(--cp-statusbar, #007acc)',
        'cp-activitybar': 'var(--cp-activitybar, #333333)',
        'cp-tab-active': 'var(--cp-tab-active, #1e1e1e)',
        'cp-tab-inactive': 'var(--cp-tab-inactive, #2d2d2d)',
        'cp-border': 'var(--cp-border, #3c3c3c)',
        'cp-text': 'var(--cp-text, #ffffff)',
        'cp-text-dim': 'var(--cp-text-dim, #b0b0b0)',
        'cp-accent': 'var(--cp-accent, #007acc)',
        'cp-success': 'var(--cp-success, #4ec9b0)',
        'cp-error': 'var(--cp-error, #f44747)',
        'cp-warning': 'var(--cp-warning, #cca700)',
        'cp-info': 'var(--cp-info, #3794ff)',
      },
      fontFamily: {
        sans: ['Inter', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
        mono: ['Consolas', 'Monaco', 'Courier New', 'monospace'],
      },
      fontSize: {
        xs: ['0.75rem', { lineHeight: '1rem' }],
        sm: ['0.875rem', { lineHeight: '1.25rem' }],
        base: ['1rem', { lineHeight: '1.5rem' }],
        lg: ['1.125rem', { lineHeight: '1.75rem' }],
        xl: ['1.25rem', { lineHeight: '1.75rem' }],
        '2xl': ['1.5rem', { lineHeight: '2rem' }],
        '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
        '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
      },
      spacing: {
        '0.5': '0.125rem',
        '1.5': '0.375rem',
        '2.5': '0.625rem',
        '3.5': '0.875rem',
      },
      borderRadius: {
        '4xl': '2rem',
      },
      boxShadow: {
        'glow': '0 0 15px rgba(0, 122, 204, 0.5)',
        'glow-lg': '0 0 30px rgba(0, 122, 204, 0.5)',
      },
      transitionDuration: {
        '400': '400ms',
      },
      zIndex: {
        '60': '60',
        '70': '70',
        '80': '80',
        '90': '90',
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-out',
        'animate-in': 'fadeIn 0.3s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0', transform: 'translateY(4px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
    },
  },
  plugins: [],
};
