name: Build Mobile APK

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      buildType:
        description: 'Build type'
        required: true
        default: 'release'
        type: choice
        options:
          - release
          - debug

env:
  ANDROID_HOME: /usr/local/lib/android/sdk

jobs:
  build:
    name: Test With Inputs
    runs-on: ubuntu-latest
    steps:
      - name: Simple check
        run: echo "Workflow is running with inputs!"
