packages:
  - 'electron'
  - 'frontend'
  - 'core'
allowBuilds:
  'electron': true
  'esbuild': true
  'ssh2': true
  'cpu-features': true
  'keytar': true
  'unrs-resolver': true
  '@vscode/vsce-sign': true
  'node-pty': true
  better-sqlite3: set this to true or false
